version: "3"
services:
    app:
        args:
            - PORT
        build: .
        env_file: .env
        ports:
            - "${PORT}:${PORT}"
        restart: unless-stopped
    redis:
        image: redis:buster
        volumes:
            - /tmp/redis:/data
        ports:
            - "6379:6379"
        restart: unless-stopped
