version: "3"
services:
  app:
    build:
      context: .
      args:
        - PORT
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
  redis:
    image: redis:buster
    volumes:
      - /tmp/redis:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
